title: Matt's Dodecatheon Blog
author: Matt Gitzendanner
email: magitz@ufl.edu
description: > # this means to ignore newlines until "baseurl:"
  I love _Dodecatheon_ so here's a buch of photos of this cool plant!

# social links
twitter_username: @m_gitz
github_username:  @magitz

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
